package org.jcodec.containers.mp4

import org.jcodec.containers.mp4.boxes.*
import org.jcodec.platform.Platform

class SampleBoxes : Boxes() {
    init {
        clear()
        override("ap4h", VideoSampleEntry::class.java)
        override("apch", VideoSampleEntry::class.java)
        override("apcn", VideoSampleEntry::class.java)
        override("apcs", VideoSampleEntry::class.java)
        override("apco", VideoSampleEntry::class.java)
        override("hev1", VideoSampleEntry::class.java)
        override("avc1", VideoSampleEntry::class.java)
        override("cvid", VideoSampleEntry::class.java)
        override("jpeg", VideoSampleEntry::class.java)
        override("smc ", VideoSampleEntry::class.java)
        override("rle ", VideoSampleEntry::class.java)
        override("rpza", VideoSampleEntry::class.java)
        override("kpcd", VideoSampleEntry::class.java)
        override("png ", VideoSampleEntry::class.java)
        override("mjpa", VideoSampleEntry::class.java)
        override("mjpb", VideoSampleEntry::class.java)
        override("SVQ1", VideoSampleEntry::class.java)
        override("SVQ3", VideoSampleEntry::class.java)
        override("mp4v", VideoSampleEntry::class.java)
        override("dvc ", VideoSampleEntry::class.java)
        override("dvcp", VideoSampleEntry::class.java)
        override("gif ", VideoSampleEntry::class.java)
        override("h263", VideoSampleEntry::class.java)
        override("tiff", VideoSampleEntry::class.java)
        override("raw ", VideoSampleEntry::class.java)
        override("2vuY", VideoSampleEntry::class.java)
        override("yuv2", VideoSampleEntry::class.java)
        override("v308", VideoSampleEntry::class.java)
        override("v408", VideoSampleEntry::class.java)
        override("v216", VideoSampleEntry::class.java)
        override("v410", VideoSampleEntry::class.java)
        override("v210", VideoSampleEntry::class.java)
        override("m2v1", VideoSampleEntry::class.java)
        override("m1v1", VideoSampleEntry::class.java)
        override("xd5b", VideoSampleEntry::class.java)
        override("dv5n", VideoSampleEntry::class.java)
        override("jp2h", VideoSampleEntry::class.java)
        override("mjp2", VideoSampleEntry::class.java)
        override("ac-3", AudioSampleEntry::class.java)
        override("cac3", AudioSampleEntry::class.java)
        override("ima4", AudioSampleEntry::class.java)
        override("aac ", AudioSampleEntry::class.java)
        override("celp", AudioSampleEntry::class.java)
        override("hvxc", AudioSampleEntry::class.java)
        override("twvq", AudioSampleEntry::class.java)
        override(".mp1", AudioSampleEntry::class.java)
        override(".mp2", AudioSampleEntry::class.java)
        override("midi", AudioSampleEntry::class.java)
        override("apvs", AudioSampleEntry::class.java)
        override("alac", AudioSampleEntry::class.java)
        override("aach", AudioSampleEntry::class.java)
        override("aacl", AudioSampleEntry::class.java)
        override("aace", AudioSampleEntry::class.java)
        override("aacf", AudioSampleEntry::class.java)
        override("aacp", AudioSampleEntry::class.java)
        override("aacs", AudioSampleEntry::class.java)
        override("samr", AudioSampleEntry::class.java)
        override("AUDB", AudioSampleEntry::class.java)
        override("ilbc", AudioSampleEntry::class.java)
        override(Platform.stringFromBytes(byteArrayOf(0x6D, 0x73, 0x00, 0x11)), AudioSampleEntry::class.java)
        override(Platform.stringFromBytes(byteArrayOf(0x6D, 0x73, 0x00, 0x31)), AudioSampleEntry::class.java)
        override("aes3", AudioSampleEntry::class.java)
        override("NONE", AudioSampleEntry::class.java)
        override("raw ", AudioSampleEntry::class.java)
        override("twos", AudioSampleEntry::class.java)
        override("sowt", AudioSampleEntry::class.java)
        override("MAC3 ", AudioSampleEntry::class.java)
        override("MAC6 ", AudioSampleEntry::class.java)
        override("ima4", AudioSampleEntry::class.java)
        override("fl32", AudioSampleEntry::class.java)
        override("fl64", AudioSampleEntry::class.java)
        override("in24", AudioSampleEntry::class.java)
        override("in32", AudioSampleEntry::class.java)
        override("ulaw", AudioSampleEntry::class.java)
        override("alaw", AudioSampleEntry::class.java)
        override("dvca", AudioSampleEntry::class.java)
        override("QDMC", AudioSampleEntry::class.java)
        override("QDM2", AudioSampleEntry::class.java)
        override("Qclp", AudioSampleEntry::class.java)
        override(".mp3", AudioSampleEntry::class.java)
        override("mp4a", AudioSampleEntry::class.java)
        override("lpcm", AudioSampleEntry::class.java)
        override("tmcd", TimecodeSampleEntry::class.java)
        override("time", TimecodeSampleEntry::class.java)
        override("c608", SampleEntry::class.java)
        override("c708", SampleEntry::class.java)
        override("text", SampleEntry::class.java)
        override("metx", XMLMetaDataSampleEntry::class.java)
        override("mett", TextMetaDataSampleEntry::class.java)
        override("urim", URIMetaSampleEntry::class.java)

        //found in gopro video files
        override("fdsc", SampleEntry::class.java)
    }
}